### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by jmonsanto** [zoellner/sharp-heic-lambda-layer#9]
Tried building the layer and running the examples but it gives out a RuntimeError, sharp module not found. Is this still working or changes in AWS having a directory structure for Node 14 is making it not work?

**Comment by zoellner** [comment]
v2.x is for node14, v1.x is for node12
Without any details on how you build it and how you're using it I can't really help you. 
I'm using the latest version in a node14 build and lambda runtime environment without any issues.

**Comment by jmonsanto** [comment]
It works now. 

Just added a few lines based on this [suggestion ](https://stackoverflow.com/questions/59012248/code-build-to-create-lambda-layer-cannot-find-module) and this documentation on a [lambda layer structure](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html):
```
install:
    runtime-versions:
      nodejs: 14
    commands:
      - pip3 install aws-sam-cli --upgrade --user
      - mkdir nodejs
      - cd nodejs
 artifacts:
  files:
    - node_modules/**/*
    - package.json
 ```
